# -*- coding: utf-8 -*-
"""v3.2PPGBPRandomForestModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWSjPm7yYJW9gyGqSOuQEr-qXGqRJN06
"""

# ================================================================
# PPG → BP  |  Multi-Test Evaluation + Poster Figures
#
# Runs any number of predict sessions in one call, then produces:
#   1. Bland-Altman plot  (the clinical gold-standard accuracy plot)
#   2. Predicted vs True scatter with regression line
#   3. Error distribution (violin + box)
#   4. Per-session error table
#   5. Cumulative accuracy bar (% within 5 / 10 / 15 mmHg)
#   6. Single combined poster panel (export-ready at 300 dpi)
#
# USAGE
# ─────
# 1. Keep SKIP_TRAIN = True if you already ran v3 Phase 1.
# 2. Fill CAL_SESSIONS (same as v3 — used to build the personalised model).
# 3. Fill TEST_SESSIONS with every file you want to evaluate.
#    Format: (path, true_SBP_or_None, true_DBP_or_None, label)
#    Label is a short string shown in plots, e.g. "Resting-1".
# 4. Set POSTER_SAVE_PATH to where you want the PNG saved.
# ================================================================

import os, glob, warnings, joblib, copy
import numpy as np
import pandas as pd

from scipy.signal  import find_peaks, butter, filtfilt, hilbert
from scipy.stats   import skew, kurtosis, iqr, trim_mean
from scipy.fft     import rfft, rfftfreq

import matplotlib
matplotlib.use("Agg")          # comment this out inside Colab if you want inline display
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import FancyBboxPatch
from matplotlib.lines import Line2D
import matplotlib.ticker as mticker

from sklearn.model_selection    import GroupShuffleSplit, KFold
from sklearn.metrics            import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble           import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model       import ElasticNetCV, RidgeCV, Ridge
from sklearn.pipeline           import Pipeline
from sklearn.impute             import SimpleImputer
from sklearn.preprocessing      import StandardScaler
from sklearn.feature_selection  import f_regression, VarianceThreshold
import xgboost as xgb

warnings.filterwarnings("ignore")

# ════════════════════════════════════════════════════════════
# !! CONFIGURE HERE !!
# ════════════════════════════════════════════════════════════
BASE        = "/content/drive/MyDrive/ppg_subjects/IRLSubjects"
MODEL_DIR   = "/content/drive/MyDrive/bp_models_v3"
WFPPG_DIR   = "/content/drive/MyDrive/ppg_subjects"
SKIP_TRAIN  = True    # True = load saved v3 models; False = retrain from scratch

FIGURES_DIR = "/content/drive/MyDrive/bp_figures"   # folder — one PNG per panel
POSTER_SAVE_PATH = "/content/drive/MyDrive/bp_accuracy_poster.png"  # combined poster (still saved too)
POSTER_DPI  = 300   # 300 = print-quality for both individual and combined

# Calibration sessions (same as v3 — first session is reference baseline)
CAL_SESSIONS = [
    (f"{BASE}/ppg_2026-04-06-01-s117d66p54.csv",     117, 66),
    (f"{BASE}/ppg_2026-04-06-02-s118d65-p65.csv",    118, 65),
    (f"{BASE}/ppg_2026-03-25-5.csv",                 None, 68),
    (f"{BASE}/ppg_2026-04-06-s116d68p65.csv",        116, 68),
]

# ── ALL TEST SESSIONS ────────────────────────────────────────
# Format: (path, true_SBP_or_None, true_DBP, label)
# Add every file you want in the accuracy table + plots.
# If you don't know SBP, use None — DBP-only metrics will still work.
TEST_SESSIONS = [
    (f"{BASE}/ppg_2026-04-06-03-s121d63p63.csv",  121, 63,  "Session A"),
    (f"{BASE}/ppg_2026-04-08-01-s123-d69-p55.csv",  123, 69,  "Session B"),
    (f"{BASE}/ppg_2026-04-08-02-s115-d68-p55.csv",  115, 68,  "Session C"),
    (f"{BASE}/ppg_2026-04-08-03-s124-d66-p53.csv",  124, 66,  "Session D"),
    (f"{BASE}/ppg_2026-04-08-04-s116-d64-p60.csv",  116, 64,  "Session E"),
    (f"{BASE}/ppg_2026-04-10-01-s117d69p67.csv",  117, 69,  "Session F"),
    (f"{BASE}/ppg_2026-04-10-02-s116d68p66.csv",  116, 68,  "Session G"),
    (f"{BASE}/ppg_2026-04-10-03-s120d67p70.csv",  120, 67,  "Session H"),
    (f"{BASE}/ppg_2026-04-10-04-s119d64p67.csv",  119, 64,  "Session I"),
    (f"{BASE}/ppg_2026-04-10-05-s114d68p73.csv",  114, 68,  "Session J"),


    # Add more rows below as you collect data:
    # (f"{BASE}/ppg_2026-04-08-01.csv",  115, 71,  "Session B"),
    # (f"{BASE}/ppg_2026-04-08-02.csv",  119, 68,  "Session C"),
    # (f"{BASE}/ppg_2026-04-09-01.csv",  122, 72,  "Session D"),
    # (f"{BASE}/ppg_2026-04-10-01.csv",  116, 65,  "Session E"),
]

# ── WF-PPG column / file config ───────────────────────────────
SBP_COL  = "BP_Sys"
DBP_COL  = "BP_Dia"
FILE_KW  = "preprocessed"
CHANNEL_PRIORITY = [
    "PPG_Wrist_G_AC","PPG_Wrist_IR","PPG_Wrist_R",
    "PPG_Finger_IR","ir_led","red_led",
]

# Signal processing (must match v3)
WINDOW_SEC           = 20    # was 30 — shorter windows give more of them from short recordings
STEP_SEC             = 5     # was 15 — denser overlap recovers far more windows per file
MIN_BEATS_PER_WINDOW = 5     # was 6 — still plenty for morphology features
MIN_HR, MAX_HR       = 38, 185  # fractionally wider to catch edge cases
MAX_CV_RR            = 0.45  # was 0.35 — real-world HRV and posture push CV_RR above 0.35

TOP_K_BASE   = 80
CORR_THRESH  = 0.95
MIN_CAL_FOR_RIDGE = 3

RF_PARAMS  = dict(n_estimators=600,max_depth=12,min_samples_leaf=2,
                  max_features="sqrt",random_state=42,n_jobs=-1)
ENET_L1    = [0.05,0.1,0.2,0.5,0.8,0.95,1.0]
XGB_PARAMS = dict(n_estimators=500,max_depth=4,learning_rate=0.04,
                  subsample=0.75,colsample_bytree=0.75,min_child_weight=3,
                  reg_alpha=0.1,reg_lambda=1.0,random_state=42,n_jobs=-1,verbosity=0)
GBM_PARAMS = dict(n_estimators=400,max_depth=4,learning_rate=0.05,
                  subsample=0.8,min_samples_leaf=3,random_state=42)
STACK_ALPHAS = [0.001,0.01,0.1,1.0,10.0,100.0]
RIDGE_ALPHAS = [0.01,0.1,1.0,10.0,100.0,1000.0]
META_COLS = ["subject","file_name","session_num","sbp","dbp",
             "channel","n_windows_good","n_windows_total"]
EPS = 1e-8

# ════════════════════════════════════════════════════════════
# POSTER STYLE  (white background, black text — print-ready)
# ════════════════════════════════════════════════════════════
DARK_BG   = "#ffffff"   # figure background
PANEL_BG  = "#ffffff"   # axes background
GRID_COL  = "#cccccc"   # grid / divider lines
TEXT_COL  = "#111111"   # primary text
MUTED_COL = "#555555"   # secondary / annotation text
SBP_COL_P = "#c0392b"   # SBP — deep red
DBP_COL_P = "#1a6eb5"   # DBP — deep blue
OK_COL    = "#1e8449"   # green  (within tolerance)
WARN_COL  = "#b7770d"   # amber  (marginal)
ERR_COL   = "#c0392b"   # red    (outside tolerance)

plt.rcParams.update({
    "figure.facecolor": DARK_BG,  "axes.facecolor":  PANEL_BG,
    "axes.edgecolor":   GRID_COL, "axes.labelcolor": TEXT_COL,
    "axes.titlecolor":  TEXT_COL, "xtick.color":     TEXT_COL,
    "ytick.color":      TEXT_COL, "text.color":      TEXT_COL,
    "grid.color":       GRID_COL, "grid.linewidth":  0.6,
    "legend.facecolor": "#ffffff","legend.edgecolor": GRID_COL,
    "legend.labelcolor": TEXT_COL,
    "font.family":      "monospace", "figure.dpi":   150,
    "axes.spines.top":  False, "axes.spines.right": False,
    "axes.spines.left": True,  "axes.spines.bottom": True,
})

# ════════════════════════════════════════════════════════════
# ──  ALL SIGNAL / FEATURE CODE BELOW IS IDENTICAL TO v3  ──
# (copied so this file is fully self-contained)
# ════════════════════════════════════════════════════════════
def infer_fs(df):
    if "timestamp_ms" in df.columns:
        dt=df["timestamp_ms"].diff().median()
        if dt and dt>0: return 1000.0/dt
    return 100.0

def bandpass(x,fs,low=0.5):
    high=min(8.0,fs/2.0-0.5)
    if high<=low: return x.astype(float)
    b,a=butter(4,[low/(fs/2),high/(fs/2)],btype="band")
    return filtfilt(b,a,x.astype(float))

def normalise(x):
    lo,hi=np.min(x),np.max(x); return (x-lo)/(hi-lo+EPS)

def _safe(fn,x): x=np.asarray(x,float);x=x[np.isfinite(x)];return fn(x) if len(x) else np.nan
def s_mean(x):  return _safe(np.mean,x)
def s_std(x):   return _safe(np.std,x)
def s_med(x):   return _safe(np.median,x)
def s_min(x):   return _safe(np.min,x)
def s_max(x):   return _safe(np.max,x)
def s_iqr(x):   return _safe(iqr,x)
def s_rms(x):
    x=np.asarray(x,float);x=x[np.isfinite(x)];return float(np.sqrt(np.mean(x**2))) if len(x) else np.nan
def s_mad(x):
    x=np.asarray(x,float);x=x[np.isfinite(x)]
    return float(np.median(np.abs(x-np.median(x)))) if len(x) else np.nan
def s_skew(x):
    x=np.asarray(x,float);x=x[np.isfinite(x)]
    return float(skew(x)) if (len(x)>=3 and np.std(x)>EPS) else np.nan
def s_kurt(x):
    x=np.asarray(x,float);x=x[np.isfinite(x)]
    return float(kurtosis(x)) if (len(x)>=4 and np.std(x)>EPS) else np.nan
def s_corr(a,b):
    a=np.asarray(a,float);b=np.asarray(b,float)
    m=np.isfinite(a)&np.isfinite(b);a,b=a[m],b[m]
    return float(np.corrcoef(a,b)[0,1]) if (len(a)>=2 and np.std(a)>EPS and np.std(b)>EPS) else np.nan
def zcr(x):
    x=np.asarray(x,float);x=x[np.isfinite(x)]
    if len(x)<2: return 0
    s=np.sign(x);s[s==0]=1;return int(np.sum(s[1:]!=s[:-1]))

def agg_stats(feats,prefix,vals):
    vals=np.asarray(vals,float);vals=vals[np.isfinite(vals)]
    for nm,fn in [("mean",np.mean),("std",np.std),("med",np.median),
                  ("min",np.min),("max",np.max),("iqr",iqr)]:
        feats[f"{prefix}_{nm}"]=fn(vals) if len(vals) else np.nan
    feats[f"{prefix}_cv"]=np.std(vals)/(np.mean(vals)+EPS) if len(vals) else np.nan

def detect_peaks_ppg(ppg, fs):
    """
    Two-pass peak detector.
    Pass 1 — standard prominence (0.3×std): catches clean signals.
    Pass 2 — relaxed prominence (0.1×std) + height filter: rescues low-amplitude
             or dampened signals (common at low contact pressure / high FS).
    Returns whichever pass found more peaks, preferring pass 1 on a tie.
    """
    md = max(int(0.33 * fs), 1)

    # Pass 1: standard
    prom1 = max(np.std(ppg) * 0.30, EPS)
    peaks1, props1 = find_peaks(ppg, distance=md, prominence=prom1)

    if len(peaks1) >= MIN_BEATS_PER_WINDOW:
        return peaks1, props1   # good enough, use it

    # Pass 2: softer prominence, add minimum height above 20th percentile
    prom2  = max(np.std(ppg) * 0.10, EPS)
    height = np.percentile(ppg, 20)
    peaks2, props2 = find_peaks(ppg, distance=md, prominence=prom2, height=height)

    # Use whichever gave more peaks; pass 1 wins on tie (higher quality)
    return (peaks2, props2) if len(peaks2) > len(peaks1) else (peaks1, props1)

def window_ok(ppg, fs):
    """
    Quality gate with a soft pre-check: attempt to clean the signal with
    a tighter bandpass before rejecting on CV_RR, to avoid discarding windows
    that only fail because of baseline wander rather than true arrhythmia.
    """
    peaks, _ = detect_peaks_ppg(ppg, fs)
    if len(peaks) < MIN_BEATS_PER_WINDOW:
        return False

    rr = np.diff(peaks) / fs
    if len(rr) < 2:
        return False

    hr = 60.0 / (np.mean(rr) + EPS)
    if not (MIN_HR <= hr <= MAX_HR):
        return False

    cv = np.std(rr) / (np.mean(rr) + EPS)
    if cv <= MAX_CV_RR:
        return True   # passes outright

    # Soft rescue: high CV_RR can be caused by missed/spurious peaks from baseline
    # wander. Rerun on a more aggressively high-pass filtered copy (1.0 Hz instead
    # of 0.5 Hz) to remove slow drift. Accept if CV_RR drops below threshold.
    try:
        nyq  = fs / 2.0
        high = min(8.0, nyq - 0.5)
        if high > 1.0:
            b, a   = butter(4, [1.0 / nyq, high / nyq], btype="band")
            ppg_hp = filtfilt(b, a, ppg)
            ppg_hp = normalise(ppg_hp)
            peaks2, _ = detect_peaks_ppg(ppg_hp, fs)
            if len(peaks2) >= MIN_BEATS_PER_WINDOW:
                rr2 = np.diff(peaks2) / fs
                hr2 = 60.0 / (np.mean(rr2) + EPS)
                cv2 = np.std(rr2) / (np.mean(rr2) + EPS)
                if (MIN_HR <= hr2 <= MAX_HR) and cv2 <= MAX_CV_RR:
                    return True
    except Exception:
        pass

    return False

def resample1d(x,n=100):
    x=np.asarray(x,float)
    if len(x)<2: return np.full(n,np.nan)
    return np.interp(np.linspace(0,1,n),np.linspace(0,1,len(x)),x)

def spectral_feats(x,fs):
    feats={}
    keys=["spec_dom_freq","spec_centroid","spec_bw","spec_entropy","spec_power",
          "spec_p05_3","spec_p3_8","spec_ratio","spec_fund","spec_h2","spec_h3",
          "spec_harm","spec_h3_ratio"]
    if len(x)<16 or np.std(x)<EPS:
        for k in keys: feats[k]=np.nan; return feats
    x0=x-np.mean(x);yf=np.abs(rfft(x0))**2;xf=rfftfreq(len(x0),d=1/fs)
    pt=np.sum(yf)+EPS;df_=xf[np.argmax(yf[1:])+1]
    cent=np.sum(xf*yf)/pt;bw=np.sqrt(np.sum(((xf-cent)**2)*yf)/pt)
    p=yf/pt;ent=-np.sum(p*np.log(p+EPS))
    b1=(xf>=0.5)&(xf<=3.0);b2=(xf>3.0)&(xf<=8.0)
    fi=np.argmin(np.abs(xf-df_))
    h2i=np.argmin(np.abs(xf-2*df_)) if np.isfinite(df_) else 0
    h3i=np.argmin(np.abs(xf-3*df_)) if np.isfinite(df_) else 0
    feats.update({"spec_dom_freq":df_,"spec_centroid":cent,"spec_bw":bw,
                  "spec_entropy":ent,"spec_power":pt,"spec_p05_3":np.sum(yf[b1]),
                  "spec_p3_8":np.sum(yf[b2]),"spec_ratio":np.sum(yf[b1])/(np.sum(yf[b2])+EPS),
                  "spec_fund":yf[fi],"spec_h2":yf[h2i] if h2i<len(yf) else np.nan,
                  "spec_h3":yf[h3i] if h3i<len(yf) else np.nan,
                  "spec_harm":yf[h2i]/(yf[fi]+EPS) if h2i<len(yf) else np.nan,
                  "spec_h3_ratio":yf[h3i]/(yf[fi]+EPS) if h3i<len(yf) else np.nan})
    return feats

def apg_features(ppg,fs):
    feats={}
    try:
        d1=np.gradient(ppg)*fs; d2=np.gradient(d1)*fs
        peaks_ppg,_=detect_peaks_ppg(ppg,fs)
        if len(peaks_ppg)<3: raise ValueError()
        ba_ratios=[];cda_ratios=[];aix_vals=[];ai2_vals=[]
        back=max(int(0.45*fs),1)
        for i,pk in enumerate(peaks_ppg):
            ss=max(0,pk-back);seg=ppg[ss:pk+1]
            if len(seg)<3: continue
            foot=ss+np.argmin(seg)
            nxt=peaks_ppg[i+1] if i<len(peaks_ppg)-1 else min(len(ppg)-1,pk+int(0.9*fs))
            if nxt<=foot+4: continue
            beat_d2=d2[foot:nxt]; bl=len(beat_d2)
            if bl<10: continue
            pos_a,_=find_peaks(beat_d2[:int(bl*0.40)],prominence=np.std(beat_d2)*0.1+EPS)
            if not len(pos_a): continue
            a_idx=pos_a[0];a_val=beat_d2[a_idx]
            if a_val<EPS: continue
            neg_b,_=find_peaks(-beat_d2[a_idx:int(bl*0.60)],prominence=np.std(beat_d2)*0.05+EPS)
            if not len(neg_b): continue
            b_val=beat_d2[a_idx+neg_b[0]]
            ba_ratios.append(b_val/(a_val+EPS))
            beat_ppg=ppg[foot:nxt]; p1i=np.argmax(beat_ppg); p1v=beat_ppg[p1i]
            ds=min(p1i+max(int(0.10*len(beat_ppg)),2),len(beat_ppg)-1)
            if ds<len(beat_ppg):
                p2c,_=find_peaks(beat_ppg[ds:],prominence=np.std(beat_ppg)*0.05+EPS)
                if len(p2c):
                    p2v=beat_ppg[ds+p2c[0]]
                    aix_vals.append(float((p2v-p1v)/(p1v-beat_ppg[0]+EPS)))
                    ai2_vals.append(float(p2v/(p1v+EPS)))
        agg_stats(feats,"apg_ba",ba_ratios);agg_stats(feats,"apg_cda",cda_ratios)
        agg_stats(feats,"apg_aix",aix_vals);agg_stats(feats,"apg_ai2",ai2_vals)
        agg_stats(feats,"apg_d2",d2);feats["apg_d2_pos_frac"]=float(np.mean(d2>0))
    except Exception:
        for p in ["apg_ba","apg_cda","apg_aix","apg_ai2","apg_d2"]:
            for s in ["_mean","_std","_med","_min","_max","_iqr","_cv"]: feats[f"{p}{s}"]=np.nan
        feats["apg_d2_pos_frac"]=np.nan
    return feats

def extract_features(ppg,fs):
    feats={}
    x=np.asarray(ppg,float);xc=x-np.mean(x)
    d1=np.gradient(x)*fs;d2=np.gradient(d1)*fs
    for nm,arr in [("sig",x),("sigc",xc),("d1",d1),("d2",d2)]:
        for stat,fn in [("mean",s_mean),("std",s_std),("med",s_med),("min",s_min),
                        ("max",s_max),("iqr",s_iqr),("mad",s_mad),("rms",s_rms),
                        ("skew",s_skew),("kurt",s_kurt),
                        ("ptp",lambda a:float(np.ptp(a))),("zcr",zcr)]:
            feats[f"{nm}_{stat}"]=fn(arr)
    feats["d1_pos_frac"]=float(np.mean(d1>0))
    feats["d1_pos_area"]=float(np.trapz(np.clip(d1,0,None),dx=1/fs))
    feats["d1_neg_area"]=float(np.trapz(np.clip(-d1,0,None),dx=1/fs))
    feats["d2_pos_area"]=float(np.trapz(np.clip(d2,0,None),dx=1/fs))
    feats["d2_neg_area"]=float(np.trapz(np.clip(-d2,0,None),dx=1/fs))
    feats["d1_energy"]=float(np.mean(d1**2));feats["d2_energy"]=float(np.mean(d2**2))
    feats["d1_d2_ratio"]=float(np.mean(d1**2)/(np.mean(d2**2)+EPS))
    try:
        env=np.abs(hilbert(xc))
        feats.update({"env_mean":float(np.mean(env)),"env_std":float(np.std(env)),
                      "env_cv":float(np.std(env)/(np.mean(env)+EPS)),
                      "env_range":float(np.max(env)-np.min(env))})
    except: [feats.__setitem__(k,np.nan) for k in ["env_mean","env_std","env_cv","env_range"]]
    feats.update(spectral_feats(x,fs)); feats.update(apg_features(x,fs))
    peaks,props=detect_peaks_ppg(x,fs); dur=len(x)/fs
    feats["peak_count"]=len(peaks);feats["peak_rate"]=len(peaks)/dur if dur>0 else np.nan
    agg_stats(feats,"peak_prom",props.get("prominences",np.array([])) if props else [])
    if len(peaks)>=2:
        rr=np.diff(peaks)/fs
        feats.update({"rr_mean":float(np.mean(rr)),"rr_std":float(np.std(rr)),
                      "rr_med":float(np.median(rr)),"rr_iqr":float(iqr(rr)),
                      "rr_cv":float(np.std(rr)/(np.mean(rr)+EPS)),
                      "hr":float(60.0/(np.mean(rr)+EPS)),
                      "rmssd":float(np.sqrt(np.mean(np.diff(rr)**2))),
                      "sdnn":float(np.std(rr)),"pnn50":float(np.mean(np.abs(np.diff(rr))>0.05))})
        drr=np.diff(rr)
        feats.update({"drr_mean":s_mean(drr),"drr_std":s_std(drr),
                      "drr_abs":s_mean(np.abs(drr)),"drr_rms":s_rms(drr)})
    else:
        for k in ["rr_mean","rr_std","rr_med","rr_iqr","rr_cv","hr","rmssd","sdnn","pnn50",
                  "drr_mean","drr_std","drr_abs","drr_rms"]: feats[k]=np.nan
    amps=[];rises=[];decays=[];w25=[];w50=[];w75=[]
    bareas=[];sareas=[];dareas=[];sup=[];sdn=[];bdurs=[];sym=[]
    nttp=[];nw50=[];inflection_ratios=[];diastolic_fracs=[]
    beat_skews=[];beat_kurts=[];beat_entropies=[];tc=[];tr=[];beats_n=[]
    back=max(int(0.45*fs),1)
    for i,pk in enumerate(peaks):
        ss=max(0,pk-back);seg=x[ss:pk+1]
        if len(seg)<3: continue
        foot=ss+np.argmin(seg)
        nxt=peaks[i+1] if i<len(peaks)-1 else min(len(x)-1,pk+int(0.9*fs))
        if nxt<=foot+2: continue
        beat=x[foot:nxt]
        if len(beat)<6: continue
        amp=x[pk]-x[foot];rt=(pk-foot)/fs;dt=(nxt-pk)/fs;bd=(nxt-foot)/fs
        if amp<=0 or not np.isfinite(rt) or rt<=0: continue
        amps.append(amp);rises.append(rt);decays.append(dt);bdurs.append(bd)
        sup.append(amp/(rt+EPS));sdn.append(amp/(dt+EPS))
        ba=float(np.trapz(beat,dx=1/fs));sa=float(np.trapz(x[foot:pk+1],dx=1/fs))
        if nxt>pk: da=float(np.trapz(x[pk:nxt],dx=1/fs));dareas.append(da);diastolic_fracs.append(da/(ba+EPS))
        bareas.append(ba);sareas.append(sa);sym.append(rt/(dt+EPS))
        d1b=np.gradient(beat)*fs
        nc,_=find_peaks(-d1b[int(len(d1b)*0.3):int(len(d1b)*0.7)],prominence=np.std(d1b)*0.1+EPS)
        if len(nc):
            n0=int(len(d1b)*0.3)+nc[0]
            if 0<n0<len(beat)-1:
                as_=float(np.trapz(beat[:n0],dx=1/fs));ad_=float(np.trapz(beat[n0:],dx=1/fs))
                inflection_ratios.append(as_/(as_+ad_+EPS))
        b0=beat-beat[0];sc_=np.max(b0)-np.min(b0)
        if sc_>EPS:
            bn=b0/sc_;beat_skews.append(float(skew(bn)) if len(bn)>=3 else np.nan)
            beat_kurts.append(float(kurtosis(bn)) if len(bn)>=4 else np.nan)
            h,_=np.histogram(bn,bins=10,density=True);h=h[h>0]
            beat_entropies.append(float(-np.sum(h*np.log(h+EPS))))
            bnr=resample1d(bn,100);beats_n.append(bnr)
            nttp.append(float(np.argmax(bnr)/99.0))
            i50=np.where(bnr>=0.5*np.max(bnr))[0]
            if len(i50)>1: nw50.append(float((i50[-1]-i50[0])/99.0))
        for frac,store in [(0.25,w25),(0.5,w50),(0.75,w75)]:
            lv=x[foot]+frac*amp;li=np.where(x[foot:pk+1]>=lv)[0]
            if not len(li): continue
            ri=np.where(x[pk:nxt]<=lv)[0]
            if not len(ri): continue
            if pk+ri[0]>foot+li[0]: store.append((pk+ri[0]-foot-li[0])/fs)
    for nm,vals in [("beat_amp",amps),("beat_rise",rises),("beat_decay",decays),
                    ("beat_dur",bdurs),("beat_w25",w25),("beat_w50",w50),("beat_w75",w75),
                    ("beat_area",bareas),("beat_sa",sareas),("beat_da",dareas),
                    ("beat_sup",sup),("beat_sdn",sdn),("beat_sym",sym),("nttp",nttp),
                    ("nw50",nw50),("beat_ipar",inflection_ratios),("beat_dfrac",diastolic_fracs),
                    ("beat_skew",beat_skews),("beat_kurt",beat_kurts),("beat_ent",beat_entropies)]:
        agg_stats(feats,nm,vals)
    feats["beat_ar"]=feats["beat_sa_mean"]/(feats["beat_da_mean"]+EPS)
    feats["beat_wr2550"]=feats["beat_w25_mean"]/(feats["beat_w50_mean"]+EPS)
    feats["beat_wr5075"]=feats["beat_w50_mean"]/(feats["beat_w75_mean"]+EPS)
    feats["beat_ud"]=feats["beat_sup_mean"]/(feats["beat_sdn_mean"]+EPS)
    feats["beat_rd"]=feats["beat_rise_mean"]/(feats["beat_decay_mean"]+EPS)
    feats["beat_stiffness_proxy"]=feats["beat_w50_mean"]*feats["rr_mean"]/(feats["beat_amp_mean"]+EPS)
    if len(beats_n)>=2:
        bna=np.asarray(beats_n,float);tpl=np.nanmedian(bna,axis=0)
        for b in bna: tc.append(s_corr(b,tpl));tr.append(float(np.sqrt(np.nanmean((b-tpl)**2))))
        agg_stats(feats,"tmpl_corr",tc);agg_stats(feats,"tmpl_rmse",tr)
        feats.update({"tmpl_area":float(np.trapz(tpl,dx=1/99)),"tmpl_max":float(np.max(tpl)),
                      "tmpl_ptp":float(np.ptp(tpl)),"tmpl_ttp":float(np.argmax(tpl)/99.0)})
    else:
        for k in ["tmpl_corr_mean","tmpl_corr_std","tmpl_corr_med","tmpl_corr_min","tmpl_corr_max",
                  "tmpl_corr_iqr","tmpl_corr_cv","tmpl_rmse_mean","tmpl_rmse_std","tmpl_rmse_med",
                  "tmpl_rmse_min","tmpl_rmse_max","tmpl_rmse_iqr","tmpl_rmse_cv",
                  "tmpl_area","tmpl_max","tmpl_ptp","tmpl_ttp"]: feats[k]=np.nan
    return feats

def pick_channel(df):
    for col in CHANNEL_PRIORITY:
        if col in df.columns: return col
    return None

def load_ppg(path,preferred_col=None):
    df=pd.read_csv(path);df.columns=df.columns.str.strip()
    fs=infer_fs(df);col=preferred_col or pick_channel(df)
    if col is None: raise ValueError(f"No PPG column in {path}")
    raw=df[col].dropna().astype(float).values; ppg=normalise(bandpass(raw,fs))
    sbp=float(df[SBP_COL].iloc[0]) if SBP_COL in df.columns else None
    dbp=float(df[DBP_COL].iloc[0]) if DBP_COL in df.columns else None
    return ppg,fs,sbp,dbp,col

def extract_windows(ppg, fs, verbose=False):
    """
    Slide windows across ppg, run quality gate, extract features from passing windows.
    verbose=True prints a short rejection breakdown (useful for debugging low yield).
    """
    win  = int(WINDOW_SEC * fs)
    step = int(STEP_SEC   * fs)
    if win < 2:
        return [], 0

    windows = [ppg[s:s+win] for s in range(0, len(ppg) - win + 1, step)]

    if verbose:
        n_few_peaks = n_bad_hr = n_high_cv = n_ok = 0
        for w in windows:
            peaks, _ = detect_peaks_ppg(w, fs)
            if len(peaks) < MIN_BEATS_PER_WINDOW: n_few_peaks += 1; continue
            rr = np.diff(peaks) / fs
            if len(rr) < 2: n_few_peaks += 1; continue
            hr = 60.0 / (np.mean(rr) + EPS)
            if not (MIN_HR <= hr <= MAX_HR): n_bad_hr += 1; continue
            cv = np.std(rr) / (np.mean(rr) + EPS)
            if cv > MAX_CV_RR: n_high_cv += 1; continue
            n_ok += 1
        print(f"    Window breakdown: total={len(windows)}  "
              f"ok={n_ok}  few_peaks={n_few_peaks}  bad_hr={n_bad_hr}  "
              f"high_cv={n_high_cv}  (after soft rescue)")

    good = [extract_features(w, fs) for w in windows if window_ok(w, fs)]
    return good, len(windows)

def aggregate_windows(feat_list):
    if not feat_list: return {}
    df=pd.DataFrame(feat_list)
    out={}
    for col in df.columns:
        vals=df[col].astype(float).dropna().values
        out[col]=float(trim_mean(vals,0.1)) if len(vals)>=4 else (float(np.mean(vals)) if len(vals) else np.nan)
    return out

# ════════════════════════════════════════════════════════════
# STACKED ENSEMBLE  (identical to v3)
# ════════════════════════════════════════════════════════════
class StackedEnsemble:
    def __init__(self):
        self.base={
            "rf":  RandomForestRegressor(**RF_PARAMS),
            "enet":Pipeline([("m",ElasticNetCV(l1_ratio=ENET_L1,cv=5,random_state=42,max_iter=20000))]),
            "xgb": xgb.XGBRegressor(**XGB_PARAMS),
            "gbm": GradientBoostingRegressor(**GBM_PARAMS),
        }
        self.meta=RidgeCV(alphas=STACK_ALPHAS); self.fitted=False

    def fit(self,X_train,y_train,n_folds=5):
        kf=KFold(n_splits=n_folds,shuffle=True,random_state=42)
        oof=np.zeros((len(X_train),len(self.base)))
        for fold,(tr_i,val_i) in enumerate(kf.split(X_train)):
            for j,(nm,m) in enumerate(self.base.items()):
                m_=copy.deepcopy(m);m_.fit(X_train[tr_i],y_train[tr_i])
                oof[val_i,j]=m_.predict(X_train[val_i])
        self.meta.fit(oof,y_train)
        for m in self.base.values(): m.fit(X_train,y_train)
        self.fitted=True; return self

    def predict(self,X):
        bp=np.column_stack([m.predict(X) for m in self.base.values()])
        return self.meta.predict(bp)

    def predict_with_uncertainty(self,X):
        bp=np.column_stack([m.predict(X) for m in self.base.values()])
        return self.meta.predict(bp),np.std(bp,axis=1)

def load_trained(model_dir):
    trained={}
    for mode in ["abs","delta"]:
        trained[mode]={}
        for target in (["sbp","dbp"] if mode=="abs" else ["sbp_delta","dbp_delta"]):
            p=os.path.join(model_dir,f"{mode}_{target}.joblib")
            if os.path.exists(p): trained[mode][target]=joblib.load(p)
    return trained

def prep_X(df,target_col,train_mask=None,top_k=TOP_K_BASE,ref_cols=None):
    skip=[c for c in META_COLS+["sbp","dbp","sbp_delta","dbp_delta","ref_sbp","ref_dbp"] if c in df.columns]
    feat_cols=[c for c in df.columns if c not in skip]
    X_df=df[feat_cols].copy()
    if ref_cols is not None: X_df=X_df.reindex(columns=ref_cols,fill_value=np.nan)
    X_df=X_df.dropna(axis=1,how="all")
    Xtmp=X_df.fillna(X_df.median(numeric_only=True))
    vt=VarianceThreshold(0.0);vt.fit(Xtmp);X_df=X_df[X_df.columns[vt.get_support()]]
    Xc=X_df.fillna(X_df.median(numeric_only=True)).corr().abs()
    upper=Xc.where(np.triu(np.ones(Xc.shape),k=1).astype(bool))
    drop=[c for c in upper.columns if any(upper[c]>CORR_THRESH)]
    X_df=X_df.drop(columns=drop);all_cols=list(X_df.columns)
    imp=SimpleImputer(strategy="median");scaler=StandardScaler()
    X_np=X_df.values.astype(float)
    if train_mask is not None:
        imp.fit(X_np[train_mask]);X_imp=imp.transform(X_np);scaler.fit(X_imp[train_mask])
    else: X_imp=imp.fit_transform(X_np);scaler.fit(X_imp)
    X_s=scaler.transform(X_imp)
    y=df[target_col].values.astype(float)
    y_sel=y[train_mask] if train_mask is not None else y
    X_sel=X_s[train_mask] if train_mask is not None else X_s
    scores,_=f_regression(X_sel,y_sel);scores=np.nan_to_num(scores)
    k_eff=min(top_k,X_s.shape[1]);idx=np.argsort(scores)[::-1][:k_eff]
    return X_s[:,idx],[all_cols[i] for i in idx],imp,scaler,idx,all_cols

def _apply_model(obj,feat_dict):
    all_cols=obj["all_cols"];sel_idx=obj["sel_idx"]
    X_df=pd.DataFrame([feat_dict]).reindex(columns=all_cols,fill_value=np.nan)
    X_imp=obj["imp"].transform(X_df.values.astype(float))
    X_s=obj["scaler"].transform(X_imp)[:,sel_idx]
    return float(obj["stack"].predict(X_s)[0])

# ════════════════════════════════════════════════════════════
# CALIBRATION  (identical to v3)
# ════════════════════════════════════════════════════════════
def run_calibration(trained, cal_sessions):
    cal_records=[]
    for path,sbp_label,dbp_label in cal_sessions:
        try:
            ppg,fs,_,_,col=load_ppg(path)
            print(f"  {os.path.basename(path)}  col={col}  fs={fs:.1f}Hz  dur={len(ppg)/fs:.1f}s")
            good,n_total=extract_windows(ppg,fs,verbose=True)
            print(f"    → {len(good)}/{n_total} windows accepted")
            if not good: continue
            fd=aggregate_windows(good)
            cal_records.append({"feat":fd,"sbp":sbp_label,"dbp":dbp_label,"file":os.path.basename(path)})
        except Exception as e:
            print(f"  Cal skip {os.path.basename(path)}: {e}")

    if not cal_records: raise RuntimeError("No usable cal sessions.")

    cal_obj={"trained":trained,"records":cal_records,"cal":{}}
    ref=cal_records[0]

    for bp_key in ["sbp","dbp"]:
        delta_key=f"{bp_key}_delta"
        y_true_d=[];y_pred_d=[];y_true_a=[];y_pred_a=[]
        for rec in cal_records[1:]:
            if rec[bp_key] is None or ref[bp_key] is None: continue
            true_delta=rec[bp_key]-ref[bp_key]
            feat_d={}
            for k in ref["feat"]:
                rv=ref["feat"].get(k,np.nan);sv=rec["feat"].get(k,np.nan)
                feat_d[f"diff__{k}"]=sv-rv if (np.isfinite(rv) and np.isfinite(sv)) else np.nan
                feat_d[f"ratio__{k}"]=sv/(rv+EPS) if (np.isfinite(rv) and np.isfinite(sv)) else np.nan
                feat_d[f"raw__{k}"]=sv
            if delta_key in trained.get("delta",{}):
                pred_d=_apply_model(trained["delta"][delta_key],feat_d)
                y_pred_d.append(pred_d);y_true_d.append(true_delta)
            if bp_key in trained.get("abs",{}):
                pred_a=_apply_model(trained["abs"][bp_key],rec["feat"])
                y_pred_a.append(pred_a);y_true_a.append(float(rec[bp_key]))

        n_d=len(y_true_d)
        if n_d>=MIN_CAL_FOR_RIDGE:
            y_t=np.array(y_true_d);y_p=np.array(y_pred_d)
            rc=RidgeCV(alphas=RIDGE_ALPHAS,cv=n_d);rc.fit(y_p.reshape(-1,1),y_t)
            cal_obj["cal"][bp_key]={"method":"ridge_delta","ridge_d":rc,"n_d":n_d}
        elif n_d>0:
            offset_d=float(np.mean(np.array(y_true_d)-np.array(y_pred_d)))
            cal_obj["cal"][bp_key]={"method":"offset_delta","offset_d":offset_d,"n_d":n_d}
        elif len(y_true_a)>0:
            offset_a=float(np.mean(np.array(y_true_a)-np.array(y_pred_a)))
            cal_obj["cal"][bp_key]={"method":"offset_abs","offset_a":offset_a}
        else:
            cal_obj["cal"][bp_key]={"method":"none"}

        cal_obj[f"ref_{bp_key}"]=ref[bp_key]
        cal_obj["ref_feat"]=ref["feat"]

    return cal_obj

# ════════════════════════════════════════════════════════════
# PREDICT ONE FILE  (identical to v3 core)
# ════════════════════════════════════════════════════════════
def predict_file(cal_obj, path):
    ppg,fs,_,_,col=load_ppg(path)
    good,n_total=extract_windows(ppg,fs,verbose=True)
    print(f"    → {len(good)}/{n_total} windows accepted")
    if not good: return None, ppg, fs, n_total

    trained=cal_obj["trained"]; ref_feat=cal_obj.get("ref_feat",{})

    results={}
    for bp_key in ["sbp","dbp"]:
        delta_key=f"{bp_key}_delta"; ref_bp=cal_obj.get(f"ref_{bp_key}")
        cal_info=cal_obj["cal"].get(bp_key,{"method":"none"})
        per_win=[]; per_unc=[]

        for wf in good:
            pred_final=None; unc=0.0
            if delta_key in trained.get("delta",{}) and ref_feat and ref_bp is not None:
                feat_d={}
                for k in ref_feat:
                    rv=ref_feat.get(k,np.nan);sv=wf.get(k,np.nan)
                    feat_d[f"diff__{k}"]=sv-rv if (np.isfinite(rv) and np.isfinite(sv)) else np.nan
                    feat_d[f"ratio__{k}"]=sv/(rv+EPS) if (np.isfinite(rv) and np.isfinite(sv)) else np.nan
                    feat_d[f"raw__{k}"]=sv
                obj=trained["delta"][delta_key]
                all_c=obj["all_cols"];sel_i=obj["sel_idx"]
                X_df=pd.DataFrame([feat_d]).reindex(columns=all_c,fill_value=np.nan)
                X_imp=obj["imp"].transform(X_df.values.astype(float))
                X_s=obj["scaler"].transform(X_imp)[:,sel_i]
                pd_arr,unc_arr=obj["stack"].predict_with_uncertainty(X_s)
                pd_val=float(pd_arr[0]);unc=float(unc_arr[0])
                m=cal_info["method"]
                if m=="ridge_delta": pd_cal=float(cal_info["ridge_d"].predict([[pd_val]])[0])
                elif m=="offset_delta": pd_cal=pd_val+cal_info.get("offset_d",0.0)
                else: pd_cal=pd_val
                pred_final=ref_bp+pd_cal
            if pred_final is None and bp_key in trained.get("abs",{}):
                obj=trained["abs"][bp_key]
                X_df=pd.DataFrame([wf]).reindex(columns=obj["all_cols"],fill_value=np.nan)
                X_imp=obj["imp"].transform(X_df.values.astype(float))
                X_s=obj["scaler"].transform(X_imp)[:,obj["sel_idx"]]
                pa,ua=obj["stack"].predict_with_uncertainty(X_s)
                pa=float(pa[0]);unc=float(ua[0])
                m=cal_info["method"]
                pred_final=pa+cal_info.get("offset_a",0.0) if m=="offset_abs" else pa
            if pred_final is not None: per_win.append(pred_final);per_unc.append(unc)

        if not per_win:
            results[bp_key]={"pred":np.nan,"std":np.nan,"ci_low":np.nan,"ci_high":np.nan,
                             "per_window":np.array([]),"n_windows":0}; continue
        preds=np.array(per_win); pred=float(np.mean(preds)); std=float(np.std(preds))
        unc_mean=float(np.mean(per_unc)) if per_unc else std
        half_ci=max(1.96*std,unc_mean)
        results[bp_key]={"pred":pred,"std":std,"ci_low":pred-half_ci,"ci_high":pred+half_ci,
                         "per_window":preds,"n_windows":len(preds)}
    return results, ppg, fs, n_total

# ════════════════════════════════════════════════════════════
# MULTI-TEST RUNNER
# ════════════════════════════════════════════════════════════
def run_all_tests(cal_obj, test_sessions):
    """
    Returns a list of result dicts, one per test session.
    Each dict: label, path, true_sbp, true_dbp,
               pred_sbp, pred_dbp, err_sbp, err_dbp,
               ci_sbp, ci_dbp, n_windows, ppg, fs
    """
    print("\n" + "="*68)
    print("MULTI-TEST EVALUATION")
    print("="*68)
    print(f"{'Label':<20} {'Pred SBP':>9} {'True SBP':>9} {'Err SBP':>8} "
          f"{'Pred DBP':>9} {'True DBP':>9} {'Err DBP':>8} {'Win':>4}")
    print("─"*80)

    all_results = []
    for path, true_sbp, true_dbp, label in test_sessions:
        try:
            res, ppg, fs, n_total = predict_file(cal_obj, path)
            if res is None:
                print(f"  {label:<18} NO GOOD WINDOWS"); continue

            pred_sbp = res["sbp"]["pred"]
            pred_dbp = res["dbp"]["pred"]
            err_sbp  = (pred_sbp - true_sbp) if (true_sbp and np.isfinite(pred_sbp)) else None
            err_dbp  = (pred_dbp - true_dbp) if (true_dbp and np.isfinite(pred_dbp)) else None

            row = dict(label=label, path=path,
                       true_sbp=true_sbp, true_dbp=true_dbp,
                       pred_sbp=pred_sbp, pred_dbp=pred_dbp,
                       err_sbp=err_sbp,   err_dbp=err_dbp,
                       ci_sbp=(res["sbp"]["ci_low"], res["sbp"]["ci_high"]),
                       ci_dbp=(res["dbp"]["ci_low"], res["dbp"]["ci_high"]),
                       n_windows=res["dbp"]["n_windows"],
                       ppg=ppg, fs=fs)
            all_results.append(row)

            def fmt(v): return f"{v:+6.1f}" if v is not None else "  N/A "
            print(f"  {label:<18} {pred_sbp:>9.1f} {str(true_sbp):>9} {fmt(err_sbp):>8} "
                  f"{pred_dbp:>9.1f} {str(true_dbp):>9} {fmt(err_dbp):>8} "
                  f"{res['dbp']['n_windows']:>4}")
        except Exception as e:
            print(f"  {label:<18} ERROR: {e}")

    # Aggregate stats
    sbp_errs = [abs(r["err_sbp"]) for r in all_results if r["err_sbp"] is not None]
    dbp_errs = [abs(r["err_dbp"]) for r in all_results if r["err_dbp"] is not None]
    print("─"*80)
    if sbp_errs:
        print(f"  SBP  MAE={np.mean(sbp_errs):.1f}  RMSE={np.sqrt(np.mean(np.array(sbp_errs)**2)):.1f}  "
              f"max={np.max(sbp_errs):.1f} mmHg  (n={len(sbp_errs)})")
    if dbp_errs:
        print(f"  DBP  MAE={np.mean(dbp_errs):.1f}  RMSE={np.sqrt(np.mean(np.array(dbp_errs)**2)):.1f}  "
              f"max={np.max(dbp_errs):.1f} mmHg  (n={len(dbp_errs)})")
    print(f"  AAMI grade A threshold: ≤5 mmHg MAE")
    return all_results

# ════════════════════════════════════════════════════════════
# POSTER FIGURES
# ════════════════════════════════════════════════════════════
def _error_color(err):
    ae=abs(err)
    if ae<=5: return OK_COL
    if ae<=10: return WARN_COL
    return ERR_COL

def _savefig(fig, path, dpi):
    """Save a figure with consistent dark-background settings and close it."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fig.savefig(path, dpi=dpi, bbox_inches="tight",
                facecolor=DARK_BG, edgecolor="none")
    plt.close(fig)
    print(f"  Saved → {path}")


def _make_fig(w, h, title_str=None):
    """Create a blank figure with optional centred title."""
    fig = plt.figure(figsize=(w, h), facecolor=DARK_BG)
    if title_str:
        fig.text(0.5, 0.97, title_str, ha="center", va="top",
                 fontsize=13, fontweight="bold",
                 color=TEXT_COL, fontfamily="monospace")
    return fig


def _prep_rows(all_results):
    sbp_rows = [(r["true_sbp"], r["pred_sbp"], r["err_sbp"], r["label"])
                for r in all_results if r["true_sbp"] and r["err_sbp"] is not None]
    dbp_rows = [(r["true_dbp"], r["pred_dbp"], r["err_dbp"], r["label"])
                for r in all_results if r["true_dbp"] and r["err_dbp"] is not None]
    return sbp_rows, dbp_rows


def save_figures(all_results, figures_dir=None, dpi=POSTER_DPI,
                 title="Cuffless Blood Pressure Estimation via Wrist PPG"):
    """
    Save every panel as its own PNG inside figures_dir.

    Files produced:
      01_bland_altman_sbp.png
      02_bland_altman_dbp.png
      03_scatter_sbp.png
      04_scatter_dbp.png
      05_error_violin.png
      06_cumulative_accuracy.png
      07_session_table.png
      08_per_session_error_bars.png
      09_summary_stats.png
      10_clinical_table.png

    Returns a dict mapping panel name → save path.
    """
    if figures_dir is None:
        figures_dir = FIGURES_DIR
    os.makedirs(figures_dir, exist_ok=True)

    sbp_rows, dbp_rows = _prep_rows(all_results)
    saved = {}

    def _path(name):
        return os.path.join(figures_dir, name)

    print(f"\n[Saving individual panel PNGs → {figures_dir}]")

    # ── 01  Bland-Altman SBP ─────────────────────────────────
    fig = _make_fig(7, 6)
    ax  = fig.add_axes([0.12, 0.12, 0.82, 0.78])
    _bland_altman(ax, sbp_rows, "SBP", SBP_COL_P)
    p = _path("01_bland_altman_sbp.png")
    _savefig(fig, p, dpi); saved["bland_altman_sbp"] = p

    # ── 02  Bland-Altman DBP ─────────────────────────────────
    fig = _make_fig(7, 6)
    ax  = fig.add_axes([0.12, 0.12, 0.82, 0.78])
    _bland_altman(ax, dbp_rows, "DBP", DBP_COL_P)
    p = _path("02_bland_altman_dbp.png")
    _savefig(fig, p, dpi); saved["bland_altman_dbp"] = p

    # ── 03  Combined scatter (SBP + DBP) ──────────────────────
    fig = _make_fig(6, 6)
    ax  = fig.add_axes([0.13, 0.12, 0.82, 0.78])
    _scatter_pred_true(ax, sbp_rows, dbp_rows)
    p = _path("03_scatter_combined.png")
    _savefig(fig, p, dpi); saved["scatter_combined"] = p

    # ── 05  Error violin ─────────────────────────────────────
    fig = _make_fig(6, 6)
    ax  = fig.add_axes([0.13, 0.12, 0.82, 0.78])
    _error_violin(ax, sbp_rows, dbp_rows)
    p = _path("05_error_violin.png")
    _savefig(fig, p, dpi); saved["error_violin"] = p

    # ── 06  Cumulative accuracy ───────────────────────────────
    fig = _make_fig(7, 6)
    ax  = fig.add_axes([0.12, 0.12, 0.82, 0.78])
    _cumulative_accuracy(ax, sbp_rows, dbp_rows)
    p = _path("06_cumulative_accuracy.png")
    _savefig(fig, p, dpi); saved["cumulative_accuracy"] = p

    # ── 07  Per-session table ─────────────────────────────────
    n_sess  = len(all_results)
    fig_h   = max(4, 1.2 + n_sess * 0.45)   # grows with session count
    fig = _make_fig(10, fig_h)
    ax  = fig.add_axes([0.02, 0.02, 0.96, 0.92])
    _session_table(ax, all_results)
    p = _path("07_session_table.png")
    _savefig(fig, p, dpi); saved["session_table"] = p

    # ── 08  Per-session error bars ────────────────────────────
    fig_w = max(8, 2 + n_sess * 1.1)
    fig = _make_fig(fig_w, 6)
    ax  = fig.add_axes([0.10, 0.14, 0.86, 0.76])
    _per_session_bars(ax, all_results)
    p = _path("08_per_session_error_bars.png")
    _savefig(fig, p, dpi); saved["per_session_error_bars"] = p

    # ── 09  Summary stats ────────────────────────────────────
    fig = _make_fig(5, 6)
    ax  = fig.add_axes([0.05, 0.05, 0.90, 0.90])
    _summary_stats_panel(ax, sbp_rows, dbp_rows)
    p = _path("09_summary_stats.png")
    _savefig(fig, p, dpi); saved["summary_stats"] = p

    # ── 10  Clinical table ───────────────────────────────────
    n_rows  = 2 + n_sess          # Mean + SD + per-session
    fig_h   = max(4, 1.5 + n_rows * 0.50)
    fig = _make_fig(16, fig_h)
    ax  = fig.add_axes([0.01, 0.08, 0.98, 0.84])
    _clinical_table(ax, sbp_rows, dbp_rows, all_results)
    p = _path("10_clinical_table.png")
    _savefig(fig, p, dpi); saved["clinical_table"] = p

    print(f"\n  {len(saved)} panel PNGs saved to {figures_dir}/")
    return saved


def make_poster(all_results, save_path=None, dpi=POSTER_DPI,
                title="PPG Cuffless BP Estimation"):
    """
    Produces a single combined poster figure AND saves every panel
    individually via save_figures().

    Layout (4 columns × 4 rows):
      Row 0:  [BA SBP] [BA DBP] [Scatter SBP] [Scatter DBP]
      Row 1:  [Violin] [Cumulative accuracy] [Per-session table (spans 2)]
      Row 2:  [Per-session error bars (spans 3)] [Summary stats]
      Row 3:  [Clinical-style summary table (spans all 4)]
    """
    sbp_rows, dbp_rows = _prep_rows(all_results)

    # ── Save individual PNGs first ────────────────────────────
    save_figures(all_results, dpi=dpi, title=title)

    # ── Build combined poster ─────────────────────────────────
    fig = plt.figure(figsize=(26, 20), facecolor=DARK_BG)
    gs  = gridspec.GridSpec(4, 4, figure=fig, hspace=0.55, wspace=0.40,
                            left=0.06, right=0.97, top=0.93, bottom=0.04)

    fig.text(0.5, 0.967, title, ha="center", va="top",
             fontsize=24, fontweight="bold", color=TEXT_COL, fontfamily="monospace")
    fig.text(0.5, 0.945,
             f"n = {len(all_results)} test sessions  |  "
             "IR wrist PPG → BP  |  Stacked ensemble (RF + ENet + XGB + GBM) + delta calibration",
             ha="center", va="top", fontsize=12, color=MUTED_COL, fontfamily="monospace")

    ax_ba_sbp = fig.add_subplot(gs[0, 0]); _bland_altman(ax_ba_sbp, sbp_rows, "SBP", SBP_COL_P)
    ax_ba_dbp = fig.add_subplot(gs[0, 1]); _bland_altman(ax_ba_dbp, dbp_rows, "DBP", DBP_COL_P)
    ax_scatter = fig.add_subplot(gs[0, 2:4]); _scatter_pred_true(ax_scatter, sbp_rows, dbp_rows)

    ax_violin = fig.add_subplot(gs[1, 0]); _error_violin(ax_violin, sbp_rows, dbp_rows)
    ax_cum    = fig.add_subplot(gs[1, 1]); _cumulative_accuracy(ax_cum, sbp_rows, dbp_rows)
    ax_table  = fig.add_subplot(gs[1, 2:4]); _session_table(ax_table, all_results)

    ax_bar    = fig.add_subplot(gs[2, 0:3]); _per_session_bars(ax_bar, all_results)
    ax_stats  = fig.add_subplot(gs[2, 3]);   _summary_stats_panel(ax_stats, sbp_rows, dbp_rows)

    ax_clin   = fig.add_subplot(gs[3, :]); _clinical_table(ax_clin, sbp_rows, dbp_rows, all_results)

    if save_path:
        fig.savefig(save_path, dpi=dpi, bbox_inches="tight",
                    facecolor=DARK_BG, edgecolor="none")
        print(f"\n  Combined poster saved → {save_path}  ({dpi} dpi)")

    plt.show()
    return fig

# ════════════════════════════════════════════════════════════
# SUB-PLOT HELPERS
# ════════════════════════════════════════════════════════════

def _bland_altman(ax, rows, target, color):
    if len(rows) < 2:
        ax.text(0.5, 0.5, "Need ≥2 sessions", ha="center", va="center",
                color=MUTED_COL, transform=ax.transAxes)
        ax.set_facecolor(PANEL_BG); return

    trues = np.array([r[0] for r in rows])
    preds = np.array([r[1] for r in rows])
    means = (trues + preds) / 2
    diffs = preds - trues
    bias  = np.mean(diffs)
    loa   = 1.96 * np.std(diffs)

    ax.scatter(means, diffs, color=color, s=80, alpha=0.85, zorder=3, edgecolors="none")
    for m, d, lbl in zip(means, diffs, [r[3] for r in rows]):
        ax.annotate(lbl, (m, d), textcoords="offset points", xytext=(4, 4),
                    fontsize=8, color=MUTED_COL)

    xmin, xmax = means.min() - 5, means.max() + 5
    ax.axhline(bias,       color=color,    lw=1.5, ls="--", label=f"Bias {bias:+.1f}")
    ax.axhline(bias + loa, color=WARN_COL, lw=1.0, ls=":",  label=f"+1.96σ {bias+loa:+.1f}")
    ax.axhline(bias - loa, color=WARN_COL, lw=1.0, ls=":",  label=f"−1.96σ {bias-loa:+.1f}")
    ax.axhline(0,          color=MUTED_COL, lw=0.6, alpha=0.4)
    ax.fill_between([xmin, xmax], bias - loa, bias + loa, color=color, alpha=0.07)
    ax.set_xlim(xmin, xmax)
    ax.set_xlabel("Mean of predicted & reference (mmHg)", fontsize=9)
    ax.set_ylabel("Predicted − Reference (mmHg)", fontsize=9)
    ax.set_title(f"Bland-Altman  —  {target}", fontsize=10, fontweight="bold")
    ax.legend(fontsize=7, loc="upper right", framealpha=0.8)
    ax.grid(True, alpha=0.2); ax.set_facecolor(PANEL_BG)


def _scatter_pred_true(ax, sbp_rows, dbp_rows):
    """Combined predicted vs Reference scatter — SBP and DBP on one axes, no fit line."""
    ax.set_facecolor(PANEL_BG)
    all_vals = []
    for rows, color, label in [(sbp_rows, SBP_COL_P, "SBP"), (dbp_rows, DBP_COL_P, "DBP")]:
        if not rows:
            continue
        trues = np.array([r[0] for r in rows])
        preds = np.array([r[1] for r in rows])
        ax.scatter(trues, preds, color=color, s=90, alpha=0.85, zorder=3,
                   edgecolors="none", label=label)

        # Point labels (ax.annotate) removed from here

        all_vals.extend(trues.tolist() + preds.tolist())

    if not all_vals:
        ax.text(0.5, 0.5, "No data", ha="center", va="center",
                color=MUTED_COL, transform=ax.transAxes); return

    lo = min(all_vals) - 5
    hi = max(all_vals) + 5
    ax.plot([lo, hi], [lo, hi], color=MUTED_COL, lw=0.8, ls="--", alpha=0.6, label="Identity")
    ax.set_xlim(lo, hi); ax.set_ylim(lo, hi)
    ax.set_xlabel("Reference (mmHg)", fontsize=9)
    ax.set_ylabel("Predicted (mmHg)", fontsize=9)
    ax.set_title("Predicted vs Reference", fontsize=10, fontweight="bold")
    ax.legend(fontsize=8, framealpha=0.8)
    ax.grid(True, alpha=0.3)
    ax.set_aspect("equal", "box")

def _error_violin(ax, sbp_rows, dbp_rows):
    data, labels, colors = [], [], []
    if sbp_rows:
        data.append([r[2] for r in sbp_rows]); labels.append("SBP"); colors.append(SBP_COL_P)
    if dbp_rows:
        data.append([r[2] for r in dbp_rows]); labels.append("DBP"); colors.append(DBP_COL_P)

    ax.set_facecolor(PANEL_BG)
    if not data:
        ax.text(0.5, 0.5, "No data", ha="center", va="center", transform=ax.transAxes); return

    positions = list(range(1, len(data) + 1))
    parts = ax.violinplot(data, positions=positions, showmedians=True,
                          showextrema=True, widths=0.6)
    for pc, col in zip(parts["bodies"], colors):
        pc.set_facecolor(col); pc.set_alpha(0.55); pc.set_edgecolor(col)
    for key in ["cmedians", "cmins", "cmaxes", "cbars"]:
        if key in parts:
            parts[key].set_color(TEXT_COL); parts[key].set_linewidth(1.2)

    rng = np.random.default_rng(42)
    for i, (d, col) in enumerate(zip(data, colors)):
        jitter = rng.uniform(-0.08, 0.08, len(d))
        ax.scatter(np.full(len(d), positions[i]) + jitter, d,
                   color=col, s=50, alpha=0.9, zorder=3, edgecolors="none")

    ax.axhline(0, color=MUTED_COL, lw=0.8, alpha=0.5)
    ax.axhspan(-5, 5, color=OK_COL, alpha=0.06, label="±5 mmHg (grade A)")
    ax.set_xticks(positions); ax.set_xticklabels(labels, fontsize=10)
    ax.set_ylabel("Error (mmHg)", fontsize=9)
    ax.set_title("Error Distribution", fontsize=10, fontweight="bold")
    ax.legend(fontsize=8, framealpha=0.8); ax.grid(True, axis="y", alpha=0.2)


def _cumulative_accuracy(ax, sbp_rows, dbp_rows):
    thresholds = [3, 5, 8, 10, 15]
    bar_w = 0.32
    xs    = np.arange(len(thresholds))
    ax.set_facecolor(PANEL_BG)

    for i, (rows, color, label) in enumerate(
            [(sbp_rows, SBP_COL_P, "SBP"), (dbp_rows, DBP_COL_P, "DBP")]):
        if not rows: continue
        errs = np.array([abs(r[2]) for r in rows])
        pcts = [100 * np.mean(errs <= t) for t in thresholds]
        offset = (i - 0.5) * bar_w
        bars = ax.bar(xs + offset, pcts, bar_w, color=color, alpha=0.8, label=label)
        for bar, pct in zip(bars, pcts):
            if pct > 0:
                ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 1,
                        f"{pct:.0f}%", ha="center", va="bottom", fontsize=8, color=color)

    ax.axhline(100, color=MUTED_COL, lw=0.6, ls="--", alpha=0.4)
    ax.set_xticks(xs)
    ax.set_xticklabels([f"≤{t}" for t in thresholds], fontsize=9)
    ax.set_xlabel("Error threshold (mmHg)", fontsize=9)
    ax.set_ylabel("% sessions within threshold", fontsize=9)
    ax.set_ylim(0, 115)
    ax.set_title("Cumulative Accuracy", fontsize=10, fontweight="bold")
    ax.legend(fontsize=8, framealpha=0.8); ax.grid(True, axis="y", alpha=0.2)


def _session_table(ax, all_results):
    ax.set_facecolor(PANEL_BG); ax.axis("off")
    if not all_results: return

    headers = ["Session", "SBP pred", "SBP ref", "SBP err",
               "DBP pred", "DBP ref", "DBP err", "Windows"]
    col_w   = [0.20, 0.11, 0.11, 0.11, 0.11, 0.11, 0.11, 0.11]
    n_rows  = len(all_results)
    row_h   = 0.82 / (n_rows + 1)

    # Header background
    ax.add_patch(FancyBboxPatch((0, 0.90), 1.0, 0.08,
                 boxstyle="round,pad=0.005", facecolor="#e8e8e8",
                 edgecolor=GRID_COL, linewidth=0.5, transform=ax.transAxes))
    x = 0.0
    for h, w in zip(headers, col_w):
        ax.text(x + w / 2, 0.945, h, ha="center", va="center",
                fontsize=8, fontweight="bold", color=TEXT_COL,
                transform=ax.transAxes)
        x += w

    for ri, r in enumerate(all_results):
        y_top = 0.88 - ri * row_h
        bg = "#f5f5f5" if ri % 2 == 0 else PANEL_BG
        ax.add_patch(FancyBboxPatch((0, y_top - row_h), 1.0, row_h,
                     boxstyle="round,pad=0.003", facecolor=bg,
                     edgecolor="none", transform=ax.transAxes))

        err_sbp = r.get("err_sbp"); err_dbp = r.get("err_dbp")
        vals = [
            r["label"],
            f"{r['pred_sbp']:.1f}" if r["pred_sbp"] else "—",
            str(r["true_sbp"])     if r["true_sbp"]  else "—",
            f"{err_sbp:+.1f}"      if err_sbp is not None else "—",
            f"{r['pred_dbp']:.1f}" if r["pred_dbp"] else "—",
            str(r["true_dbp"])     if r["true_dbp"]  else "—",
            f"{err_dbp:+.1f}"      if err_dbp is not None else "—",
            str(r.get("n_windows", "—")),
        ]
        text_colors = [TEXT_COL, TEXT_COL, TEXT_COL,
                       _error_color(err_sbp) if err_sbp is not None else TEXT_COL,
                       TEXT_COL, TEXT_COL,
                       _error_color(err_dbp) if err_dbp is not None else TEXT_COL,
                       MUTED_COL]
        x = 0.0
        for val, w, tc in zip(vals, col_w, text_colors):
            ax.text(x + w / 2, y_top - row_h / 2, val,
                    ha="center", va="center", fontsize=8.5,
                    color=tc, transform=ax.transAxes)
            x += w

    ax.set_title("Per-Session Results", fontsize=10, fontweight="bold")


def _per_session_bars(ax, all_results):
    labels   = [r["label"]   for r in all_results]
    sbp_errs = [r["err_sbp"] for r in all_results]
    dbp_errs = [r["err_dbp"] for r in all_results]

    xs = np.arange(len(labels)); w = 0.38
    ax.set_facecolor(PANEL_BG)

    for i, err in enumerate(sbp_errs):
        if err is None: continue
        ax.bar(i - w/2, err, w, color=SBP_COL_P, alpha=0.75, label="SBP" if i==0 else "")
        ax.bar(i - w/2, err, w, color=_error_color(err), alpha=0.30)

    for i, err in enumerate(dbp_errs):
        if err is None: continue
        ax.bar(i + w/2, err, w, color=DBP_COL_P, alpha=0.75, label="DBP" if i==0 else "")
        ax.bar(i + w/2, err, w, color=_error_color(err), alpha=0.30)

    ax.axhline(0, color=MUTED_COL, lw=0.8, alpha=0.5)
    ax.axhspan( 5,  99, color=WARN_COL, alpha=0.05)
    ax.axhspan(-5, -99, color=WARN_COL, alpha=0.05)
    ax.axhspan(-5,   5, color=OK_COL,   alpha=0.07, label="±5 mmHg zone")
    ax.set_xticks(xs); ax.set_xticklabels(labels, fontsize=10)
    ax.set_ylabel("Error (mmHg)\n[predicted − reference]", fontsize=9)
    ax.set_title("Per-Session Prediction Error", fontsize=10, fontweight="bold")
    handles = [
        Line2D([0],[0], color=SBP_COL_P, lw=5, alpha=0.75, label="SBP"),
        Line2D([0],[0], color=DBP_COL_P, lw=5, alpha=0.75, label="DBP"),
        Line2D([0],[0], color=OK_COL,    lw=8, alpha=0.30, label="±5 mmHg (grade A)"),
    ]
    ax.legend(handles=handles, fontsize=9, framealpha=0.8, loc="upper right")
    ax.grid(True, axis="y", alpha=0.2)


def _summary_stats_panel(ax, sbp_rows, dbp_rows):
    ax.set_facecolor(PANEL_BG); ax.axis("off")
    ax.set_xlim(0, 1); ax.set_ylim(0, 1)

    def stat_block(rows, label, color, y_start):
        if not rows: return
        errs = np.array([r[2] for r in rows])
        mae  = np.mean(np.abs(errs))
        rmse = np.sqrt(np.mean(errs**2))
        bias = np.mean(errs)
        loa  = 1.96 * np.std(errs)
        pct5 = 100 * np.mean(np.abs(errs) <= 5)
        pct_col = OK_COL if pct5 == 100 else (WARN_COL if pct5 >= 70 else ERR_COL)

        ax.text(0.05, y_start,       label,                  color=color,   fontsize=13,
                fontweight="bold", va="top", transform=ax.transAxes)
        ax.text(0.05, y_start-0.08, f"MAE:    {mae:.2f} mmHg",  color=TEXT_COL, fontsize=10,
                va="top", transform=ax.transAxes)
        ax.text(0.05, y_start-0.15, f"RMSE:   {rmse:.2f} mmHg", color=TEXT_COL, fontsize=10,
                va="top", transform=ax.transAxes)
        ax.text(0.05, y_start-0.22, f"Bias:   {bias:+.2f} mmHg",color=TEXT_COL, fontsize=10,
                va="top", transform=ax.transAxes)
        ax.text(0.05, y_start-0.29, f"±1.96σ  {loa:.2f} mmHg",  color=TEXT_COL, fontsize=10,
                va="top", transform=ax.transAxes)
        ax.text(0.05, y_start-0.36, f"≤5 mmHg: {pct5:.0f}%",    color=pct_col,  fontsize=11,
                fontweight="bold", va="top", transform=ax.transAxes)

    stat_block(sbp_rows, "SBP", SBP_COL_P, 0.95)
    ax.plot([0.0, 1.0], [0.45, 0.45], color=GRID_COL, lw=0.8, transform=ax.transAxes)
    stat_block(dbp_rows, "DBP", DBP_COL_P, 0.42)

    n = len(set([r[3] for r in sbp_rows + dbp_rows]))
    ax.text(0.5, 0.04, f"n = {n} test sessions", ha="center", va="bottom",
            fontsize=9, color=MUTED_COL, transform=ax.transAxes)
    ax.set_title("Summary Statistics", fontsize=10, fontweight="bold")


def _clinical_table(ax, sbp_rows, dbp_rows, all_results):
    """
    Clinical-style summary table matching the published paper format:
    Variable | PPG Algo SBP | PPG Algo DBP | Reference SBP | Reference DBP | SBP Err% | DBP Err%
    Rows: Mean, SD, per-session data
    """
    ax.set_facecolor(PANEL_BG); ax.axis("off")

    if not sbp_rows and not dbp_rows:
        ax.text(0.5, 0.5, "No data", ha="center", va="center",
                color=MUTED_COL, transform=ax.transAxes); return

    # ── Compute aggregate stats ───────────────────────────────
    def _stats(rows):
        if not rows: return None
        preds = np.array([r[1] for r in rows])
        trues = np.array([r[0] for r in rows])
        errs  = preds - trues
        pct_errs = (np.abs(errs) / trues) * 100
        return {"pred_mean": np.mean(preds), "pred_sd": np.std(preds, ddof=1) if len(preds)>1 else 0,
                "true_mean": np.mean(trues), "true_sd": np.std(trues, ddof=1) if len(trues)>1 else 0,
                "err_mean":  np.mean(np.abs(errs)),
                "err_sd":    np.std(np.abs(errs), ddof=1) if len(errs)>1 else 0,
                "pct_mean":  np.mean(pct_errs), "pct_sd": np.std(pct_errs, ddof=1) if len(pct_errs)>1 else 0}

    ss = _stats(sbp_rows); ds = _stats(dbp_rows)

    # ── Table geometry ────────────────────────────────────────
    # Columns: Variable | PPG SBP | PPG DBP | Ref SBP | Ref DBP | SBP Err (mmHg) | DBP Err (mmHg) | SBP Err% | DBP Err%
    col_labels = ["Variable",
                  "PPG Est.\nSBP (mmHg)", "PPG Est.\nDBP (mmHg)",
                  "Reference\nSBP (mmHg)", "Reference\nDBP (mmHg)",
                  "SBP\nError (mmHg)", "DBP\nError (mmHg)",
                  "SBP\nError (%)", "DBP\nError (%)"]
    col_x = [0.00, 0.11, 0.22, 0.33, 0.44, 0.55, 0.64, 0.73, 0.82]
    col_w = [0.11, 0.11, 0.11, 0.11, 0.11, 0.09, 0.09, 0.09, 0.09]

    header_y  = 0.90
    row_ys    = [0.68, 0.46]   # Mean row, SD row
    row_labels= ["Mean", "Standard\nDeviation"]

    total_rows = 2 + len(all_results)   # Mean + SD + per-session
    all_row_ys = [header_y - 0.22*(i+1) for i in range(total_rows)]

    # Header background
    ax.add_patch(FancyBboxPatch((0, header_y - 0.01), 1.0, 0.13,
                 boxstyle="square,pad=0", facecolor="#e8e8e8",
                 edgecolor=GRID_COL, linewidth=0.8, transform=ax.transAxes))

    # Column headers (two-line)
    for lbl, x, w in zip(col_labels, col_x, col_w):
        ax.text(x + w/2, header_y + 0.10, lbl,
                ha="center", va="top", fontsize=8, fontweight="bold",
                color=TEXT_COL, transform=ax.transAxes, linespacing=1.3)

    # Divider under header
    ax.plot([0, 1], [header_y - 0.005, header_y - 0.005],
            color=GRID_COL, lw=0.8, transform=ax.transAxes)

    def _fmt(val, fallback="—"):
        return f"{val:.2f}" if val is not None and np.isfinite(val) else fallback

    def _pct_err(pred, true):
        if pred is None or true is None or true == 0: return None
        return abs(pred - true) / true * 100

    # ── Data rows ─────────────────────────────────────────────
    # Row 0: Mean
    # Row 1: SD
    # Rows 2+: per-session
    all_data_rows = []

    # Mean row
    all_data_rows.append({
        "label": "Mean",
        "ppg_sbp":  _fmt(ss["pred_mean"] if ss else None),
        "ppg_dbp":  _fmt(ds["pred_mean"] if ds else None),
        "ref_sbp":  _fmt(ss["true_mean"] if ss else None),
        "ref_dbp":  _fmt(ds["true_mean"] if ds else None),
        "err_sbp":  _fmt(ss["err_mean"]  if ss else None),
        "err_dbp":  _fmt(ds["err_mean"]  if ds else None),
        "pct_sbp":  _fmt(ss["pct_mean"]  if ss else None),
        "pct_dbp":  _fmt(ds["pct_mean"]  if ds else None),
        "bold": True,
    })
    # SD row
    all_data_rows.append({
        "label": "Std Dev",
        "ppg_sbp":  _fmt(ss["pred_sd"] if ss else None),
        "ppg_dbp":  _fmt(ds["pred_sd"] if ds else None),
        "ref_sbp":  _fmt(ss["true_sd"] if ss else None),
        "ref_dbp":  _fmt(ds["true_sd"] if ds else None),
        "err_sbp":  _fmt(ss["err_sd"]  if ss else None),
        "err_dbp":  _fmt(ds["err_sd"]  if ds else None),
        "pct_sbp":  _fmt(ss["pct_sd"]  if ss else None),
        "pct_dbp":  _fmt(ds["pct_sd"]  if ds else None),
        "bold": False,
    })

    sbp_lookup = {r[3]: r for r in sbp_rows}
    dbp_lookup = {r[3]: r for r in dbp_rows}

    for r in all_results:
        lbl = r["label"]
        sr  = sbp_lookup.get(lbl); dr = dbp_lookup.get(lbl)
        ppg_sbp = sr[1] if sr else None; ref_sbp = sr[0] if sr else None
        ppg_dbp = dr[1] if dr else None; ref_dbp = dr[0] if dr else None
        err_sbp_v = abs(sr[2]) if sr else None
        err_dbp_v = abs(dr[2]) if dr else None
        all_data_rows.append({
            "label":   lbl,
            "ppg_sbp": _fmt(ppg_sbp), "ppg_dbp": _fmt(ppg_dbp),
            "ref_sbp": _fmt(ref_sbp), "ref_dbp": _fmt(ref_dbp),
            "err_sbp": _fmt(err_sbp_v), "err_dbp": _fmt(err_dbp_v),
            "pct_sbp": _fmt(_pct_err(ppg_sbp, ref_sbp)),
            "pct_dbp": _fmt(_pct_err(ppg_dbp, ref_dbp)),
            "bold": False,
        })

    n_data = len(all_data_rows)
    row_height = min(0.86 / n_data, 0.14)
    start_y    = header_y - 0.02

    for ri, row in enumerate(all_data_rows):
        y_top = start_y - ri * row_height

        # Alternating row backgrounds; bold rows get slightly different shade
        bg = "#e8e8e8" if row["bold"] else ("#f5f5f5" if ri % 2 == 0 else PANEL_BG)
        ax.add_patch(FancyBboxPatch((0, y_top - row_height), 1.0, row_height,
                     boxstyle="square,pad=0", facecolor=bg,
                     edgecolor="none", transform=ax.transAxes))

        cell_vals = [row["label"], row["ppg_sbp"], row["ppg_dbp"],
                     row["ref_sbp"], row["ref_dbp"],
                     row["err_sbp"], row["err_dbp"],
                     row["pct_sbp"], row["pct_dbp"]]

        # Colour error columns by magnitude
        def _err_col_from_str(s, threshold=5.0):
            try: v = float(s); return _error_color(v) if v > 0 else OK_COL
            except: return TEXT_COL

        cell_colors = [
            TEXT_COL, SBP_COL_P, DBP_COL_P,
            MUTED_COL, MUTED_COL,
            _err_col_from_str(row["err_sbp"]),
            _err_col_from_str(row["err_dbp"]),
            _err_col_from_str(row["pct_sbp"], threshold=5.0),
            _err_col_from_str(row["pct_dbp"], threshold=5.0),
        ]

        fw = "bold" if row["bold"] else "normal"
        fs = 9.5 if row["bold"] else 8.5
        y_mid = y_top - row_height / 2

        for val, x, w, tc in zip(cell_vals, col_x, col_w, cell_colors):
            ax.text(x + w/2, y_mid, val,
                    ha="center", va="center", fontsize=fs,
                    fontweight=fw, color=tc, transform=ax.transAxes)

        # Light horizontal divider after each row
        ax.plot([0, 1], [y_top - row_height, y_top - row_height],
                color=GRID_COL, lw=0.3, alpha=0.5, transform=ax.transAxes)

    # Vertical column dividers
    for x in col_x[1:]:
        ax.plot([x, x], [0, header_y + 0.12], color=GRID_COL, lw=0.3,
                alpha=0.4, transform=ax.transAxes)

    # Footer note matching paper style
    note = ("SBP (DBP) Error (%) = (|PPG Estimation Algorithm BP − Reference BP| / Reference BP) × 100  "
            "   Error (mmHg) = |PPG Estimation Algorithm BP − Reference BP|")
    ax.text(0.0, -0.04, note, ha="left", va="top", fontsize=7.5,
            color=MUTED_COL, transform=ax.transAxes, style="italic")

    ax.set_title("Clinical Summary Table", fontsize=10, fontweight="bold")

# ════════════════════════════════════════════════════════════
# ENTRY POINT
# ════════════════════════════════════════════════════════════
if __name__ == "__main__":

    # Load / train models
    if SKIP_TRAIN:
        print("[Loading saved v3 models]")
        trained = load_trained(MODEL_DIR)
    else:
        # Full retrain — imports from v3 if you've organised as a package,
        # or just paste the v3 train functions here and call them.
        raise NotImplementedError(
            "Set SKIP_TRAIN=True to use saved v3 models, "
            "or import phase1_train from ppg_bp_pipeline_v3.py"
        )

    # Calibrate
    print("\n[Calibrating]")
    cal_obj = run_calibration(trained, CAL_SESSIONS)

    # Run all tests
    results = run_all_tests(cal_obj, TEST_SESSIONS)

    # Generate poster + individual panel PNGs
    if results:
        make_poster(results,
                    save_path=POSTER_SAVE_PATH,
                    title="Cuffless Blood Pressure Estimation via Wrist PPG")
    else:
        print("No results to plot — check TEST_SESSIONS paths and signal quality.")

from google.colab import drive

drive.mount('/content/drive', force_remount=True)